datasource:
  masterDataSource:
    jdbcUrl: "${DB_HOST}"
    username: "testDBUser"
    password: "testDBPassword"
    minimumIdle: 1
    maxPoolSize: 5
    connectionTimeout: 30000
    idleTimeout: 20000
    prepStmsCacheSqlLimit: 2048
    prepStmsCacheSqlCacheSize: 256
    cachePrepStmts: true
    useServerPrepStmts: true
    poolNameSuffix: pool-master
  replicaDataSource:
    jdbcUrl: "${DB_REPLICA_HOST}"
    username: "testDBUser"
    password: "testDBPassword"
    minimumIdle: 1
    maxPoolSize: 5
    connectionTimeout: 30000
    idleTimeout: 20000
    prepStmsCacheSqlLimit: 2048
    prepStmsCacheSqlCacheSize: 256
    cachePrepStmts: true
    useServerPrepStmts: true
    poolNameSuffix: pool-replica
  overrides:
    default:
      masterDataSource:
        username: "testDBUser"
        password: "testDBPassword"
  schemaNames:
    default: public

app:
  tenants: default
  hostTenantMap: {}
  runningITMode: false

redis:
  host: "${REDIS_HOST}"
  port: ${redis.port:6379}
  mode: STANDALONE
  timeToLive: 604800000

kafka:
  bootstrapServers: "${KAFKA_HOST}"
  topics: ["testTopic"]
  retries: 3
  acks: all
  batchSize: 16384
  lingerMs: 1
  bufferMemory: 33554432
  keySerializer: org.apache.kafka.common.serialization.StringSerializer
  valueSerializer: org.apache.kafka.common.serialization.StringSerializer

spring:
  security:
    enabled: false

outbox:
  relay:
    enabled: false

management:
  server:
    port: 0
  health:
    ping:
      enabled: true
    db:
      enabled: true
    redis:
      enabled: true
