name: Verify Package
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java for publishing to maven build
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Package
        run: mvn clean package
  unit-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java for publishing to maven build
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Unit Tests
        run: mvn clean test

  integration-tests:
    runs-on: ubuntu-latest
    container:
      image: olxindia/assertx
    permissions:
      contents: read
      packages: write
    services:
      docker:
        image: docker:dind
        ports:
          - 2375:2375
        env:
          DOCKER_TLS_CERTDIR: ""
        options: >-
          --privileged
          --health-cmd "docker info"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 10s
    env:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_DRIVER: overlay2
      DOCKER_TLS_CERTDIR: ""
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v4
      - name: Run Integration Tests
        run: mvn clean integration-test -DskipUnitTests=true -Dassertx-profile=ci
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            target/surefire-reports/
            target/failsafe-reports/

