name: Verify Package
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java for publishing to maven build
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Package
        run: mvn clean package
  unit-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java for publishing to maven build
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Unit Tests
        run: mvn clean test

  integration-tests:
    runs-on: ubuntu-latest
    container:
      image: olxindia/assertx
    permissions:
      contents: read
      packages: write
    env:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_DRIVER: overlay2
      DOCKER_TLS_CERTDIR: ""
    services:
      docker:
        image: docker:dind
        options: --privileged
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Wait for Docker Daemon
        run: |
          for i in {1..10}; do
            docker info && break
            echo "Waiting for Docker Daemon..."
            sleep 3
          done
      - name: Run Integration Tests
        run: /app/execute-it.sh
