name: Verify Package
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java for publishing to maven build
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Package
        run: mvn clean package
  unit-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java for publishing to maven build
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Unit Tests
        run: mvn clean test

  integration-tests:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged
        env:
          DOCKER_TLS_CERTDIR: ""

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker CLI
        run: |
          docker version
          docker info

      - name: Run Integration Tests
        run: |
          docker run --rm \
            -e DOCKER_DRIVER=overlay2 \
            -e DOCKER_TLS_CERTDIR= \
            -v /var/run/docker.sock:/var/run/docker.sock \  # ✅ Use UNIX socket instead of TCP
            -v $(pwd):/workspace \
            -w /workspace \
            olxindia/assertx \
            ./mvnw clean integration-test -DskipUnitTests=true -Dassertx-profile=ci

      - name: Show Docker Logs if Failure
        if: failure()
        run: docker logs $(docker ps -aq --filter "name=docker")


